# This workflow will build and test all Go modules in the project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - bank
          - investment_calculator
          - profit_calculator

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      run: go build -v ./...
      working-directory: ${{ matrix.module }}

    - name: Test
      run: go test -v ./...
      working-directory: ${{ matrix.module }}
